[keys.ssh]
algorithm = "ed25519"
email = "your_email@example.com"
title = ""

[updates]
dependencies = true
system = true

[tools]
brave_browser = "latest"
code = "latest"
docker = "latest"
gh = "latest"
git = "latest"
rustc = "latest"
